name: Build and Execute Tests

on:
  push:
    branches:
      - master      
  pull_request:
    branches:
      - master
      - develop
  merge_group:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v1

      - name: Enable Assertions
        run: mv ./scalac.options.local.template ./scalac.options.local

      - name: Build Opal
        run: sbt -J-Xmx20G cleanBuild

      - name: Restore Scalac Options for Format Check
        run: mv ./scalac.options.local ./scalac.options.local.template
      
      - name: Check formatting
        run: git diff --exit-code
        
      - name: Run tests
        run: sbt -J-Xmx20G test

  it-test:
    runs-on: self-hosted
    needs: build

    if: github.event_name == 'push' || github.event_name == 'merge_group' 

    steps:
    - uses: actions/checkout@v1

    - name: Enable Assertions
      run: mv ./scalac.options.local.template ./scalac.options.local

    - name: Run Integration Tests
      run: sbt -J-Xmx40G cleanBuild it:test
